# Generated by Django 3.1 on 2020-09-03 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 3, 4, 59, 37, 156466, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviecontent',
            name='discription',
            field=models.CharField(max_length=500, null=True, verbose_name='説明欄'),
        ),
        migrations.AlterField(
            model_name='moviecontent',
            name='movie',
            field=models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='moviecontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
    ]
